![imagen](./img/ejercicios.png)

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [1]:
import numpy as np
np.__version__

'1.21.6'

## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [145]:
import numpy as np
my_array=np.arange(0,10)
print(my_array)

[0 1 2 3 4 5 6 7 8 9]


## Ejercicio 3
Crea un array 3x3, que sea todo a True

In [28]:
x = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(x)
print(x==2)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False  True False]
 [False False False]
 [False False False]]


## Ejercicio 4
Extrae todos los impares de `my_array`


In [154]:
my_array=np.arange(0,10)
mask = my_array%2 == 0
my_array[mask]=1
print(my_array)

[1 1 1 3 1 5 1 7 1 9]


In [152]:
my_array=np.arange(0,10)
mask = my_array%2 != 0
my_array[mask]=0
print(my_array)

[0 0 2 0 4 0 6 0 8 0]


## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [115]:
mask = my_array%2!=0
print(mask)

my_array[mask]=-1
print(my_array)


[[ True False  True]
 [False  True False]
 [ True False  True]]
[[-1  2 -1]
 [ 4 -1  6]
 [-1  8 -1]]


## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

In [116]:
import numpy as np

print(np.where(my_array %2!=0, -1,my_array))


[[-1  2 -1]
 [ 4 -1  6]
 [-1  8 -1]]


## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [262]:
my_array=np.arange(0,10)
print(my_array,"\n")

my_array=np.arange(10).reshape(5,2)
new=my_array
print(new)

[0 1 2 3 4 5 6 7 8 9] 

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


## Ejercicio 8
Concatena los siguientes arrays verticamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [253]:
a=np.arange(10).reshape(2,-1)
b=np.repeat(1,10).reshape(2,-1)
print(a)
print(b)
np.vstack([a, b])

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa el método `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [252]:
from functools import reduce
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento del array
3. Accede al último elemento del array
4. Imprime por pantalla los numeros del 1 al 7

In [192]:
my_array=np.arange(10)
print(my_array)
#Punto1
print(my_array[::]*10)
#Punto 2
print(my_array[0])
#Punto 3
print(my_array[-1])
#Punto 4
print(my_array[1:8])

[0 1 2 3 4 5 6 7 8 9]
[ 0 10 20 30 40 50 60 70 80 90]
0
9
[1 2 3 4 5 6 7]


## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

In [201]:
my_matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(my_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

In [213]:
prueba=np.arange(1,50,3)

print(prueba)


[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]


## Ejercicio 15
Obtén la siguiente secuencia

```Python
[4., 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2., 1.75, 1.5 ,1.25]
```

In [250]:
prueba2=np.arange(4,1,-0.25)

print(prueba2)

[4.   3.75 3.5  3.25 3.   2.75 2.5  2.25 2.   1.75 1.5  1.25]


## Ejercicio 16
Lee la imagen "numpy.png"

## Ejercicio 17
Crea un array de 4x1. A continuación convierte el array a un 2x2

In [283]:
my_array=np.array([1,2,3,4])
print(my_array)
new=my_array.reshape(2,2)

print(new)

[1 2 3 4]
[[1 2]
 [3 4]]


## Ejercicio 18
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

In [362]:
from numpy import array, random

x=np.random.randint(99,size = (4,5,3))
print(x)



[[[85 72 55]
  [96 89 84]
  [26 44 10]
  [80 73 70]
  [63 87 91]]

 [[84 30 36]
  [53 58 88]
  [75 82 84]
  [32 93 83]
  [68 46 70]]

 [[65 56 34]
  [92 81 14]
  [68 36 21]
  [15 20  7]
  [44 40  7]]

 [[ 0 32 71]
  [46 39 72]
  [68  0 78]
  [25 68 91]
  [91 40 26]]]


## Ejercicio 19
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

In [358]:
x_bools = np.array(x == 2)
print(x_bools)

y = x_bools.reshape((5,3))
print(y)


[False False False False False False False False False False  True False
 False False False]
[[False False False]
 [False False False]
 [False False False]
 [False  True False]
 [False False False]]


## Ejercicio 20
Dado el siguiente array

```Python
x =np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuántos elementos tiene cada dimensión?

In [360]:
x =np.random.randint(10, 20, size = (5,2,6))
print(x)

#5 matrices de 2 x 6

[[[12 13 13 18 14 14]
  [14 18 19 14 10 10]]

 [[13 10 17 10 15 17]
  [15 13 12 11 17 16]]

 [[10 15 14 14 12 18]
  [15 19 15 14 15 13]]

 [[10 16 19 13 18 17]
  [17 18 19 15 16 13]]

 [[17 14 18 15 11 19]
  [14 16 16 12 16 11]]]
